### ISSUE TITLE
Uploading Polypoid and Ringing Bloom fails

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#554]
```
ChkError: Section STR  does not exist
    at Map.sections.section (/home/node/shieldbattery/node_modules/bw-chk/lib/index.js:156:13)
    at new Chk (/home/node/shieldbattery/node_modules/bw-chk/lib/index.js:365:45)
    at Duplex.<anonymous> (/home/node/shieldbattery/node_modules/bw-chk/lib/index.js:389:15)
    at Duplex.emit (events.js:327:22)
    at finish (internal/streams/writable.js:657:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 ```
 
 I imagine there's some other maps that fail that way as well, probably some newer map format?

**Comment by tec27** [comment]
Fixed as of 9687bbddf2df04e2c38889a5b44d7211c4a6abfa (I think before then actually? Anyway definitely at that point)
