### ISSUE TITLE
Server crash on websocket connection

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#572]
```json
{"level":50,"time":1609028428652,"pid":8,"hostname":"6f420b3d8840","reqId":"ckj6dzdd1000q08mn69ra8pec","err":{"type":"TypeError","message":"Invalid value used as weak map key","stack":"TypeError: Invalid value used as weak map key\n    at WeakMap.set (<anonymous>)\n    at hashJSObj (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:874:15)\n    at hash (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:786:16)\n    at createNodes (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2967:39)\n    at ArrayMapNode.update (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2472:14)\n    at updateNode (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2928:17)\n    at updateMap (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2885:17)\n    at Map.set (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2314:14)\n    at Set.add (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:4269:40)\n    at /home/node/shieldbattery/node_modules/nydus/lib/index.js:178:84\n    at updateInDeeply (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2020:22)\n    at updateInDeeply (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2033:23)\n    at updateIn (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:1998:24)\n    at update (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2069:12)\n    at Map.update$1 [as update] (/home/node/shieldbattery/node_modules/immutable/dist/immutable.js:2075:9)\n    at NydusServer.subscribeClient (/home/node/shieldbattery/node_modules/nydus/lib/index.js:178:41)"},"msg":"websocket error"}
```

Not really sure why a Request wouldn't be a valid WeakMap key *some of the time*, but that seems to be the case here. First step seems to me to be ugprading Nydus+deps since that hasn't been done forever. For now I've probably fixed the crash by adding an `error` handler to Nydus, but this'll still cause some other problems most likely.

**Comment by tec27** [comment]
This particular was error was actually due to a code path in ImmutableJS used by Nydus, should definitely be fixed as of fba325d72159c6be6a7a48b8138ce4c49a875d9d
