### ISSUE TITLE
Error in gameResults service

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#621]
```json
{"level":50,"time":1615609478558,"pid":9,"hostname":"2de096c5a9a8","req":{"id":"ckm7863yi0ero09ph1m1y3uo1","method":"POST","url":"/api/1/gameResults/1f3f2deb-a01d-4dd4-8149-11200850e731","headers":{"host":"shieldbattery.net","connection":"close","x-real-ip":"-","x-forwarded-for":"-","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","content-length":"159","origin":"shieldbattery://game","x-shield-battery-client":"true","content-type":"application/json","accept":"*/*"}},"length":321,"name":"error","severity":"ERROR","code":"23505","detail":"Key (user_id, matchmaking_type, game_id)=(1930, 1v1, 1f3f2deb-a01d-4dd4-8149-11200850e731) already exists.","schema":"public","table":"matchmaking_rating_changes","constraint":"matchmaking_rating_changes_pkey","file":"nbtinsert.c","line":"563","routine":"_bt_check_unique","stack":"error: duplicate key value violates unique constraint \"matchmaking_rating_changes_pkey\"\n    at Parser.parseErrorMessage (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:357:11)\n    at Parser.handlePacket (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:186:21)\n    at Parser.parse (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:101:30)\n    at Socket.<anonymous> (/home/node/shieldbattery/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:467:12)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","type":"Error","msg":"checking for reconcilable results on submission failed"}

{"level":50,"time":1615610287935,"pid":9,"hostname":"2de096c5a9a8","req":{"id":"ckm78nghc0f4p09ph911mfnuw","method":"POST","url":"/api/1/gameResults/187faf2c-9d64-45e8-bac2-2c029242e463","headers":{"host":"shieldbattery.net","connection":"close","x-real-ip":"-","x-forwarded-for":"-","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","content-length":"156","origin":"shieldbattery://game","x-shield-battery-client":"true","content-type":"application/json","accept":"*/*"}},"length":321,"name":"error","severity":"ERROR","code":"23505","detail":"Key (user_id, matchmaking_type, game_id)=(1930, 1v1, 187faf2c-9d64-45e8-bac2-2c029242e463) already exists.","schema":"public","table":"matchmaking_rating_changes","constraint":"matchmaking_rating_changes_pkey","file":"nbtinsert.c","line":"563","routine":"_bt_check_unique","stack":"error: duplicate key value violates unique constraint \"matchmaking_rating_changes_pkey\"\n    at Parser.parseErrorMessage (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:357:11)\n    at Parser.handlePacket (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:186:21)\n    at Parser.parse (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:101:30)\n    at Socket.<anonymous> (/home/node/shieldbattery/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:467:12)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","type":"Error","msg":"checking for reconcilable results on submission failed"}
```

Seems like a game got double-reconciled (requests from both players came in at the same time an interleaved, maybe)? I think if this happens it's fine to drop the query. Perhaps we should be locking on the initial reconciliation or something though

**Comment by tec27** [comment]
Fixed by 76c8c65bcd2535adf0974ffb0dfb09c3c7152c15

**Comment by tec27** [comment]
saw another instance of this error even after the fix:
```
{"level":50,"time":1615778662808,"pid":10,"hostname":"789f130da45d","req":{"id":"ckma0wbcb07yx0ao4d4dhghuh","method":"POST","url":"/api/1/gameResults/bc4914fd-c756-4336-9e8e-3bd943a55f87","headers":{"host":"shieldbattery.net","connection":"close","x-real-ip":"","x-forwarded-for":"","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","content-length":"159","origin":"shieldbattery://game","x-shield-battery-client":"true","content-type":"application/json","accept":"*/*"}},"err":{"type":"DatabaseError","message":"duplicate key value violates unique constraint \"matchmaking_rating_changes_pkey\"","stack":"error: duplicate key value violates unique constraint \"matchmaking_rating_changes_pkey\"\n    at Parser.parseErrorMessage (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:357:11)\n    at Parser.handlePacket (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:186:21)\n    at Parser.parse (/home/node/shieldbattery/node_modules/pg-protocol/src/parser.ts:101:30)\n    at Socket.<anonymous> (/home/node/shieldbattery/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:467:12)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","length":321,"name":"error","severity":"ERROR","code":"23505","detail":"Key (user_id, matchmaking_type, game_id)=(2023, 1v1, bc4914fd-c756-4336-9e8e-3bd943a55f87) already exists.","schema":"public","table":"matchmaking_rating_changes","constraint":"matchmaking_rating_changes_pkey","file":"nbtinsert.c","line":"563","routine":"_bt_check_unique"},"msg":"checking for reconcilable results on submission failed"}
```

**Comment by tec27** [comment]
Oh I see, the previous fix didn't early return as intended, so this was handled properly but then logged an error anyway. Easy fix :)
