### ISSUE TITLE
Redis migrations fail to run

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#712]
```
Running redis migrations
> server/redis-migrations/2016-12-21-create-session-list.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../lib/redis'
Require stack:
- /home/node/shieldbattery/server/redis-migrations/2016-12-21-create-session-list.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/node/shieldbattery/server/redis-migrations/2016-12-21-create-session-list.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/node/shieldbattery/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/node/shieldbattery/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node/shieldbattery/server/redis-migrations/2016-12-21-create-session-list.js'
  ]
}
```

(This isn't a huge priority atm because we haven't added any of these in quite some time, but ideally we fix this before we need to add another one)

**Comment by 2Pacalypse-** [comment]
I'm not sure why it can't find that module. The path seems correct to me?

Maybe it assumes the wrong file extension when importing `.ts` files from a `.js` file?

**Comment by tec27** [comment]
Yeah, I assumed it could be something like that but I haven't actually investigated. The way these scripts run isn't totally the same as e.g. how our application runs so sometimes things that work in the app don't work here.
