### ISSUE TITLE
Logging out with a notification popup shown causes an exception

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#742]
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at NotificationPopups (webpack-internal:///./client/notifications/notifications-popup.tsx:69:81)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:19380)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:19380)
    at MainLayout (eval at ES6ProxyComponentFactory (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:231:68)
    at LoadingFilter (eval at ES6ProxyComponentFactory (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:231:68)
    at SiteConnectedFilter (webpack-internal:///./client/network/site-connected-filter.tsx:45:67)
overrideMethod @ react_devtools_backend.js:2574
printWarning @ react-dom.development.js?7f13:68
error @ react-dom.development.js?7f13:44
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js?7f13:23915
scheduleUpdateOnFiber @ react-dom.development.js?7f13:21841
dispatchAction @ react-dom.development.js?7f13:16140
onRest @ notifications-popup.tsx?f1ad:107
eval @ react-spring-core.esm.js?926a:513
batchedUpdates$1 @ react-dom.development.js?7f13:22381
eval @ react-spring-core.esm.js?926a:512
async function (async)
eval @ react-spring-core.esm.js?926a:493
runAsync @ react-spring-core.esm.js?926a:518
start @ react-spring-core.esm.js?926a:1657
onStart @ react-spring-core.esm.js?926a:377
onResume @ react-spring-core.esm.js?926a:364
eval @ react-spring-core.esm.js?926a:347
scheduleProps @ react-spring-core.esm.js?926a:320
flushUpdate @ react-spring-core.esm.js?926a:1644
eval @ react-spring-core.esm.js?926a:1571
flushUpdateQueue @ react-spring-core.esm.js?926a:1571
start @ react-spring-core.esm.js?926a:1470
eval @ react-spring-core.esm.js?926a:2242
each @ react-spring-shared.esm.js?9c45:33
eval @ react-spring-core.esm.js?926a:2220
commitHookEffectListMount @ react-dom.development.js?7f13:20574
commitLifeCycles @ react-dom.development.js?7f13:20635
commitLayoutEffects @ react-dom.development.js?7f13:23427
callCallback @ react-dom.development.js?7f13:3946
invokeGuardedCallbackDev @ react-dom.development.js?7f13:3995
invokeGuardedCallback @ react-dom.development.js?7f13:4057
commitRootImpl @ react-dom.development.js?7f13:23152
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?7f13:11277
commitRoot @ react-dom.development.js?7f13:22991
performSyncWorkOnRoot @ react-dom.development.js?7f13:22330
eval @ react-dom.development.js?7f13:11328
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?7f13:11277
flushSyncCallbackQueueImpl @ react-dom.development.js?7f13:11323
flushSyncCallbackQueue @ react-dom.development.js?7f13:11310
batchedUpdates$1 @ react-dom.development.js?7f13:22388
notify @ Subscription.js?79d6:19
notifyNestedSubs @ Subscription.js?79d6:90
handleChangeWrapper @ Subscription.js?79d6:95
dispatch @ redux.js?00d8:297
dispatch @ VM5130:3856
eval @ create-store.js?1300:24
eval @ index.js?b083:11
dispatch @ dispatch-registry.ts?6c24:21
loadingHandler @ socket-handlers.js?fc90:40
onPublish @ index.js?3e2c:110
onMessage @ index.js?3e2c:169
eval @ index.js?3e2c:53
Emitter.emit @ index.js?7297:145
onPacket @ socket.js?da92:401
Emitter.emit @ index.js?7297:145
onPacket @ transport.js?19b7:105
callback @ polling.js?0949:98
onData @ polling.js?0949:102
Emitter.emit @ index.js?7297:145
onData @ polling-xhr.js?d33e:231
onLoad @ polling-xhr.js?d33e:282
xhr.onreadystatechange @ polling-xhr.js?d33e:186
XMLHttpRequest.send (async)
create @ polling-xhr.js?d33e:198
Request @ polling-xhr.js?d33e:115
request @ polling-xhr.js?d33e:62
doPoll @ polling-xhr.js?d33e:90
poll @ polling.js?0949:74
onData @ polling.js?0949:111
Emitter.emit @ index.js?7297:145
onData @ polling-xhr.js?d33e:231
onLoad @ polling-xhr.js?d33e:282
xhr.onreadystatechange @ polling-xhr.js?d33e:186
XMLHttpRequest.send (async)
create @ polling-xhr.js?d33e:198
Request @ polling-xhr.js?d33e:115
request @ polling-xhr.js?d33e:62
doPoll @ polling-xhr.js?d33e:90
poll @ polling.js?0949:74
doOpen @ polling.js?0949:23
open @ transport.js?19b7:44
open @ socket.js?da92:194
Socket @ socket.js?da92:119
module.exports @ index.js?94ac:3
doConnect @ index.js?3e2c:50
connect @ index.js?3e2c:63
eval @ site-connected-filter.tsx?97c8:44
invokePassiveEffectCreate @ react-dom.development.js?7f13:23488
callCallback @ react-dom.development.js?7f13:3946
invokeGuardedCallbackDev @ react-dom.development.js?7f13:3995
invokeGuardedCallback @ react-dom.development.js?7f13:4057
flushPassiveEffectsImpl @ react-dom.development.js?7f13:23575
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?7f13:11277
flushPassiveEffects @ react-dom.development.js?7f13:23448
performSyncWorkOnRoot @ react-dom.development.js?7f13:22270
eval @ react-dom.development.js?7f13:11328
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?7f13:11277
flushSyncCallbackQueueImpl @ react-dom.development.js?7f13:11323
flushSyncCallbackQueue @ react-dom.development.js?7f13:11310
batchedUpdates$1 @ react-dom.development.js?7f13:22388
notify @ Subscription.js?79d6:19
notifyNestedSubs @ Subscription.js?79d6:90
handleChangeWrapper @ Subscription.js?79d6:95
dispatch @ redux.js?00d8:297
dispatch @ VM5130:3856
eval @ create-store.js?1300:24
eval @ index.js?b083:11
dispatch @ redux.js?00d8:659
eval @ create-store.js?1300:18
Promise.then (async)
eval @ create-store.js?1300:18
eval @ index.js?b083:11
dispatch @ redux.js?00d8:659
thunk @ action-creators.ts?5e58:49
eval @ index.js?b083:8
Login.onSubmit @ login.jsx?553e:202
FormWrapperImpl.doOnSubmit @ form.tsx?7bda:159
checkValidations @ form.tsx?7bda:232
FormWrapperImpl.onSubmit @ form.tsx?7bda:244
eval @ button.tsx?0c0c:127
callCallback @ react-dom.development.js?7f13:3946
invokeGuardedCallbackDev @ react-dom.development.js?7f13:3995
invokeGuardedCallback @ react-dom.development.js?7f13:4057
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?7f13:4071
executeDispatch @ react-dom.development.js?7f13:8244
processDispatchQueueItemsInOrder @ react-dom.development.js?7f13:8276
processDispatchQueue @ react-dom.development.js?7f13:8289
dispatchEventsForPlugins @ react-dom.development.js?7f13:8300
eval @ react-dom.development.js?7f13:8509
batchedEventUpdates$1 @ react-dom.development.js?7f13:22397
batchedEventUpdates @ react-dom.development.js?7f13:3746
dispatchEventForPluginEventSystem @ react-dom.development.js?7f13:8508
attemptToDispatchEvent @ react-dom.development.js?7f13:6006
dispatchEvent @ react-dom.development.js?7f13:5925
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?7f13:11277
discreteUpdates$1 @ react-dom.development.js?7f13:22414
discreteUpdates @ react-dom.development.js?7f13:3757
dispatchDiscreteEvent @ react-dom.development.js?7f13:5890
Show 70 more frames
```

**Comment by tec27** [comment]
Pretty sure React got rid of this warning
