### ISSUE TITLE
Match load timeout can screw up the matchmaking queue entry for a later search

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#787]
```
[2021-12-02 01:34:04.073 +0000] ERROR (19460 on DESKTOP-RFS2DBA): error while processing match
    err: {
      "type": "Error",
      "message": "Operation timed out",
      "stack":
          Error: Operation timed out
              at Timeout.<anonymous> (C:\Users\Travis\Documents\Projects\shieldbattery\common\async\/reject-on-timeout.js:4:39)
              at listOnTimeout (node:internal/timers:557:17)
              at processTimers (node:internal/timers:500:7)
    }
[2021-12-02 01:34:05.728 +0000] ERROR (19460 on DESKTOP-RFS2DBA): error while matching players
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'type')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'type')
              at Matchmaker.onMatchFound (C:\Users\Travis\Documents\Projects\shieldbattery\server\lib\matchmaking\/matchmaking-service.ts:268:55)
              at Matchmaker.matchPlayers (C:\Users\Travis\Documents\Projects\shieldbattery\server\lib\matchmaking\/matchmaker.ts:509:14)
              at LazyScheduler.method (C:\Users\Travis\Documents\Projects\shieldbattery\server\lib\matchmaking\/matchmaker.ts:300:26)
              at C:\Users\Travis\Documents\Projects\shieldbattery\server\lib\matchmaking\/lazy-scheduler.ts:112:24
 ```
 
Sequence of events:
- 4 players queued
- Match found, game load starts
- 1 player fails to load, I quit out of the 3 visible games and refreshed all the clients
- Requeue with all 4 players

Seems like the timeout came along and killed the queue entries (or something else prevented them from being inserted properly?) as the match was found, and thus when it went to retrieve the queue entry it got nothing back.

Leaves things in a bad state on the client because they still appear to be searching but will never find a match at this point.

**Comment by tec27** [comment]
The matchmaker this bug lived in (in-process TS matcher + LazyScheduler) was replaced wholesale by the Rust matchmaker (#1286). The new flow tracks requeue tickets explicitly and orders cancel/requeue operations so a match-load failure can't corrupt a later search's queue entry.
