### ISSUE TITLE
Error in closeWhisperSession

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#790]
```
Error: No rows deleted
    at closeWhisperSession (/home/node/shieldbattery/server/lib/whispers/whisper-models.ts:67:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WhisperService.closeWhisperSession (/home/node/shieldbattery/server/lib/whispers/whisper-service.ts:89:5)
    at WhisperApi.closeWhisperSession (/home/node/shieldbattery/server/lib/whispers/whisper-api.ts:109:5)
    at /home/node/shieldbattery/server/lib/http/http-api.ts:100:22
    at middlewareFunc (/home/node/shieldbattery/server/lib/throttle/middleware.ts:15:5)
    at convertWhisperServiceErrors (/home/node/shieldbattery/server/lib/whispers/whisper-api.ts:65:5)
    at ensureLoggedIn (/home/node/shieldbattery/server/lib/session/ensure-logged-in.js:8:3)
    at /home/node/shieldbattery/server/lib/session/user-sessions-middleware.js:10:5
    at /home/node/shieldbattery/server/lib/network/user-ips-middleware.js:14:5
    at secureHeaders (/home/node/shieldbattery/server/lib/security/headers.js:4:5)
    at /home/node/shieldbattery/server/lib/session/migrate-sessions.ts:31:5
```

This seems to indicate the service has bad info about open sessions here, not sure what's up (that or some other query is bugged). I'm honestly not sure that keeping state in this service is necessary or a good idea anyway, but that's a bigger change than fixing whatever is causing this bug.

**Comment by tec27** [comment]
Fixed in e7f5ad8db, which made closing whisper sessions idempotent: the DB delete reports affected rows instead of throwing, and the service short-circuits when the session isn't tracked. The crash in this stack trace can no longer occur.
