### ISSUE TITLE
Error in onMatchFound

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#794]
```
TypeError: Cannot read properties of undefined (reading 'type')
    at Matchmaker.onMatchFound (/home/node/shieldbattery/server/lib/matchmaking/matchmaking-service.ts:289:55)
    at Matchmaker.searchForMatches (/home/node/shieldbattery/server/lib/matchmaking/matchmaker.ts:607:14)
    at LazyScheduler.method (/home/node/shieldbattery/server/lib/matchmaking/matchmaker.ts:396:26)
    at /home/node/shieldbattery/server/lib/matchmaking/lazy-scheduler.ts:112:24
```

Seems likely that a player left the queue (disconnect?) as a match was found. Could probably just return early in this case under the expectation that the other players would be requeued right after?

**Comment by tec27** [comment]
The crash site was replaced along with the rest of the matchmaker in #1286. The current match-found handling checks that each matched player still has queue data and, when someone is missing, logs it and requeues/notifies the affected players instead of throwing.
