### ISSUE TITLE
Unhandled rejection in PartyService

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#847]
```
unhandled rejection
TYPE
PartyServiceError
MESSAGE
Party not found or you're not in it
Error: Party not found or you're not in it
    at PartyService.sendChatMessage (/home/node/shieldbattery/server/lib/parties/party-service.ts:334:13)
    at PartyApi.sendChatMessage (/home/node/shieldbattery/server/lib/parties/party-api.ts:252:23)
    at runMicrotasks (<anonymous>)
```

**Comment by tec27** [comment]
Doesn't seem like a lot we can really do here, this rejection *is* being handled, timing must just be such that Node reports it before that happens. Seems like we could handle https://nodejs.org/api/process.html#event-rejectionhandled and only report these periodically, rather than immediately
